### ISSUE TITLE
Incidencia en la integración de la rama guadalhorce-preferences - Funcionalidad: Preferencias

### ISSUE THREAD

**Issue by davtorcue** [davtorcue/decide#18]
Pasos a seguir para reproducir el bug:
- Entrar en tu entorno virtual
- Intentar migrar la base de datos

Salida esperada y obtenida:
- Se esperaba un mensaje diciendo que se había migrado correctamente o que no había nada que migrar.
- La salida obtenida es un error diciendo que se repetían cosas en la base de datos.

Al integrar la rama a develop-guadalhorce se han encontrado unos fallos de versionado y es necesario arregarlos para no perder nada

**Comment by antmarcab4** [comment]
Para solucionar este error, se borró la base de datos y se creó de nuevo.
