### ISSUE TITLE
Incidencia de integración de código - Arreglar problema de la rama develop

### ISSUE THREAD

**Issue by davtorcue** [davtorcue/decide#21]
Han desaparecido algunos archivos (y alomejor incluso contenido) de la rama develop y es urgente recuperar esa información.

**Comment by marperoli2** [comment]
El problema se ha solucionado gracias a que un integrante del equipo tenía en su local la rama funcionando, y se ha hecho un commit de su local en la rama develop, recuperando lo que teníamos antes de que empezaran a aparecer los problemas.
