### ISSUE TITLE
Incidencia de pruebas - Funcionalidad: Yes/No

### ISSUE THREAD

**Issue by jospearui** [davtorcue/decide#38]
**Pasos a seguir para reproducir el bug (puede añadir más pasos):**

1.- Correr los tests de Voting.

**Salida esperada y qué salida ha obtenido.**

La salida esperada es que se pasen las pruebas y se ejecuten correctamente, además también se espera que las pruebas cubran bien la funcionalidad. La salida obtenida ha sido que una de las pruebas no pasan y no hay suficientes.

**Información adicional:** Se requiere el añadido de nuevas pruebas y la modificación de alguna de las existentes

**Comment by antmarcab4** [comment]
Se han añadido tests y se han corregido los existentes mediante la adición de métodos clean en el modelo.
