### ISSUE TITLE
Incidencia de tests - Funcionalidad: integración

### ISSUE THREAD

**Issue by marperoli2** [davtorcue/decide#46]
**Pasos a seguir para reproducir el bug (puede añadir más pasos):*** 
1. Se corren todas las pruebas del sistema.

**Salida esperada y qué salida ha obtenido:**
Se espera que se pasen todas las pruebas, sin embargo esto no es así, ya que fallan algunas pruebas que no pertenecen a los módulos modificados.

**Información adicional:**
El equipo supone que esto es debido a los json que contienen algunas de las pruebas.

**Comment by antmarcab4** [comment]
Las pruebas que fallan creemos que lo hacen por variables del código en json desactualizadas, ya que una relación (votación-pregunta) se actualizó a many to many y a pesar de múltiples intentos de cambios para lograr que sean correctos no logramos que funcionaran. Por ello estas pruebas quedarán comentadas.
