### ISSUE TITLE
Incidencia sobre la propuesta de cambio – Funcionalidad: Pregunta si/no

### ISSUE THREAD

**Issue by jospearui** [davtorcue/decide#60]
**Pasos a seguir para reproducir el bug(puede añadir más pasos):** 

Crear una pregunta de si/no. 

Comprobar que se ha creado correctamente. 

**Salida esperada y qué salida ha obtenido:** 

La salida esperada es que se haya creado una pregunta de este tipo con las opciones “Sí”, “No” y “No sabe/No contesta” y la salida obtenida es que la pregunta se ha creado pero sin la última opción, dado que no está todavía implementada. 

**Información adicional:** 

El equipo realizará este cambio para la defensa del proyecto delante del profesor.

**Comment by marperoli2** [comment]
Para resolver el problema, hemos modificado el receiver añadiéndole la tercera opción de “No sabe/No contesta” y también hemos modificado el método clean que sirve para validar que las opciones son correctas. Además, hemos modificado los tests para comprobar que todo funciona bien.
